💄 Improve consistency of title-bar (windows)
adlerluiz/ytmdesktop pull request #1424
Opened 2024-08-25 18:37 UTC by XeroxDev

# Summary
This pull request enhances the title-bar to make it a bit more consistent on windows devices. It's just a small change, but IMO looks better (we've also discussed about this in discord).

# What did exactly change?
I adjusted
- the font size of the "YouTube Music Desktop App" Title
- the main icon, so it's not as huge and "out of place"
- the right icons
  - I made the icons self smaller, so it's kinda the same size as the "official" windows buttons
  - I made the buttons (clickable space) somewhat the same size, as the "official" windows buttons
  - I removed the divider, so everything has somewhat the same distance to another (at least for the eyes)

# Comparison
**Before**
![image](https://github.com/user-attachments/assets/7da9fcfe-02be-407b-85d4-cc3b9997ff0b)

**After**
![image](https://github.com/user-attachments/assets/16cb32f0-cf63-47ef-b311-917da72420fb)

# Was that needed?
Not necessarily, but I think it's looking more consistent now and less "out of place". But that's just my opinion, if you think the original one is better, feel free to decline and close this pull request

# PS
I've also added `.idea` to the .gitignore. This is the JetBrains IDE settings folder.

2024-09-06 16:27 UTC, NovusTheory requested changes
Overall looks good besides a couple nitpicks.

An overall change I'm not sure I agree with is the app buttons we add to the titlebar matching Windows explicitly. This does affect other platforms so they make look off. I'm open to changing the margin/padding but I'd rather have it look more like before where it aligns with what IntelliJ IDEA or VSCode does for extra top right titlebar buttons.

2024-09-06 16:27 UTC, NovusTheory commented on src/renderer/components/TitleBar.vue
> +  font-size: 13px;
Having tested this seems like it could be 14px as 13px seems 1 pixel too small

2024-09-06 17:04 UTC, XeroxDev commented
As requested and discussed on discord, I've changed the top right icons a bit
![image](https://github.com/user-attachments/assets/f27fa03e-25ee-4174-9e89-391063b4e34c)

2024-10-26 16:23 UTC, NovusTheory approved these changes

2024-10-26 16:23 UTC, merged