Allow to choose Dark/Light tray icon
adlerluiz/ytmdesktop pull request #1474
Opened 2024-12-04 15:01 UTC by hron

Some quick demo:

https://github.com/user-attachments/assets/183c3d54-a534-4268-94a2-77922941eda5

Closes #1356

2024-12-04 16:27 UTC, Alipoodle commented
_this is without testing and checking docs_
But trayTemplate was a specific name required for MacOS to automatically do it on that OS~
So this maybe something which breaks that functionality ~

2024-12-05 14:57 UTC, hron commented
@Alipoodle Thank you for the quick feedback! I trust you about macOS, but I think I have found a universal way to handle light/dark tray icon style which can be utilized everywhere.  https://www.electronjs.org/docs/latest/api/native-theme 

I cannot test it on macOS, but it works on Linux. The new version goes one step further and introduces a setting to either do light/dark switching automatically depending on 'Dark Mode' setting or allow the user to choose. This is useful for situation when a light theme is in use, but the panel with tray is dark. 

The updated version should work on Windows as well as you requested. Please let me know if something is missing. Also, here is new demo:

https://github.com/user-attachments/assets/672c4e47-6a98-4c96-81b8-f51b9a0ffed5

2024-12-06 02:11 UTC, NovusTheory commented
> Additionally this feels like it would be nice to also include Windows and have a Inverted .ico file as well.

The normal for Windows is usually to just use the app's colored icon and not some specialized tray icon which can flip colors like this.

While this PR is only to toggle dark/light icons I feel like if we'll be messing with the tray icon we should just try and swap to something better like maybe utilizing our black and white logos that are already in the repo (we already use the white for the titlebar). Mac is still a special case though as UI and designs there are drastically different

2024-12-06 10:18 UTC, hron commented
@NovusTheory all your feedback has been incorporated. In addition, the setting to change the tray icon style is only shown on Linux now. I think it makes sense because on macOS the app uses trayTemplate.png and on Windows it always shows the colored version of the tray icon, so the setting doesn't make any sense there.

2024-12-07 00:18 UTC, NovusTheory commented
Outside of the CSS for the select menu missing and not aligning with the rest of the app's style I'm satisfied with these changes.

2024-12-07 10:49 UTC, hron commented
Well, CSS is not my strong side, but here are some improvements:


https://github.com/user-attachments/assets/e30d5ee6-c518-4be1-9745-a41c0934ca0e

2024-12-09 00:36 UTC, NovusTheory commented
I had just got reminded of an old branch I made for something else which implemented a select menu setting https://github.com/ytmdesktop/ytmdesktop/commit/363916b3418e1e30b095ef2edc6aeb2118bc246b. After looking over the code for this PR I think I'd prefer the logic in the linked commit for our setting component. I can cherry-pick that select menu code for our setting component (YTMDSetting.vue) into the development branch and this PR could get adjusted to utilize that if you'd be willing to. If that branch had ever gotten merged then it would've already been available and ready to use for this PR.

2024-12-09 08:10 UTC, hron commented
@NovusTheory sounds good to me, please ping me when the select implementation is available in `development`, so I can rebase this branch and use the new component. Thanks!

2024-12-10 20:28 UTC, NovusTheory commented
@hron Pushed the select menu type to development and ready for use.

2024-12-11 11:31 UTC, hron commented
@NovusTheory okay, it's done and ready for another review round

2024-12-18 00:06 UTC, NovusTheory requested changes
Not sure if it would be beneficial to make the config an enum (number) instead of arbitrary text but otherwise seems okay outside a nit change.

@Alipoodle Chiming you in for thoughts on the above.

2024-12-18 00:06 UTC, NovusTheory commented on src/renderer/windows/settings/Settings.vue
> +            :options-map="toOptionsMap(trayIconStyles)"
Nit: This should capitalize the options for the UI. The actual config doesn't need it.

2024-12-18 11:41 UTC, hron commented
> Not sure if it would be beneficial to make the config an enum (number) instead of arbitrary text but otherwise seems okay outside a nit change.
> 
> @Alipoodle Chiming you in for thoughts on the above.

I have updated the codebase to use an enum (number). It definitely looks simpler on the code side, so I believe this change makes sense. Although, I had to change YTMSetting component a bit. It was working a bit incorrectly because when an option is selected the value it used for assignment was a `string` (e.g. "1"), not a `number` (e.g. 1).

Also, the options are capitalized now as requested:

![image](https://github.com/user-attachments/assets/5a157f67-87ab-41e2-b176-ec85fa682ef0)

2025-01-21 10:38 UTC, hron commented
@NovusTheory any more comments on this? I think the PR is ready for merging

2025-02-05 01:06 UTC, NovusTheory approved these changes
Sorry this took so long to get around to. LGTM

2025-02-05 01:06 UTC, merged